# - op: replace
#   path: /spec/rules/0/host
#   value: etherbank-prod.ddns.net
- op: add
  path: /metadata/annotations
  value: 
    kubernetes.io/ingress.class: nginx
- op: add
  path: /spec
  value: 
    rules:
      - host: oneblock.ddns.net
        http:
          paths:
          - backend:
              serviceName: etherbank-client-service
              servicePort: 80
