apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod

resources:
- ../base
images:
- name: seyio/etherbank-frontend
  newTag: latest
replicas:
- count: 1
  name: nginx-app-deployment
