apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-client-prod

resources:
- ../base
images:
- name: seyio/etherbank-frontend
  newTag: latest
replicas:
- count: 2
  name: etherbank-client-deployment
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: etherbank-client-ingress
    namespace: etherbank-client-prod
  path: ingress_patch.yml