apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-client-prod

resources:
- ../base
- namespace-prod.yml
images:
- name: seyio/etherbank-frontend
  newTag: bb56c7c8
patchesJson6902:
- path: ingress_patch.yml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: etherbank-client-ingress
    namespace: etherbank-client-prod
    version: v1beta1
