apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: etherbank-dev

resources:
- ../base
images:
- name: seyio/etherbank-frontend
  newTag: latest
replicas:
- count: 1
  name: etherbank-client-deployment
